/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KalpanaRouteImport } from './routes/kalpana'
import { Route as PraveshRouteImport } from './routes/pravesh'
import { Route as SamasyaRouteImport } from './routes/samasya'
import { Route as SthitiRouteImport } from './routes/sthiti'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KalpanaRoute = KalpanaRouteImport.update({
  id: '/kalpana',
  path: '/kalpana',
  getParentRoute: () => rootRouteImport,
} as any)
const PraveshRoute = PraveshRouteImport.update({
  id: '/pravesh',
  path: '/pravesh',
  getParentRoute: () => rootRouteImport,
} as any)
const SamasyaRoute = SamasyaRouteImport.update({
  id: '/samasya',
  path: '/samasya',
  getParentRoute: () => rootRouteImport,
} as any)
const SthitiRoute = SthitiRouteImport.update({
  id: '/sthiti',
  path: '/sthiti',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kalpana': typeof KalpanaRoute
  '/pravesh': typeof PraveshRoute
  '/samasya': typeof SamasyaRoute
  '/sthiti': typeof SthitiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kalpana': typeof KalpanaRoute
  '/pravesh': typeof PraveshRoute
  '/samasya': typeof SamasyaRoute
  '/sthiti': typeof SthitiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kalpana': typeof KalpanaRoute
  '/pravesh': typeof PraveshRoute
  '/samasya': typeof SamasyaRoute
  '/sthiti': typeof SthitiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kalpana' | '/pravesh' | '/samasya' | '/sthiti'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kalpana' | '/pravesh' | '/samasya' | '/sthiti'
  id: '__root__' | '/' | '/kalpana' | '/pravesh' | '/samasya' | '/sthiti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KalpanaRoute: typeof KalpanaRoute
  PraveshRoute: typeof PraveshRoute
  SamasyaRoute: typeof SamasyaRoute
  SthitiRoute: typeof SthitiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalpana': {
      id: '/kalpana'
      path: '/kalpana'
      fullPath: '/kalpana'
      preLoaderRoute: typeof KalpanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravesh': {
      id: '/pravesh'
      path: '/pravesh'
      fullPath: '/pravesh'
      preLoaderRoute: typeof PraveshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samasya': {
      id: '/samasya'
      path: '/samasya'
      fullPath: '/samasya'
      preLoaderRoute: typeof SamasyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sthiti': {
      id: '/sthiti'
      path: '/sthiti'
      fullPath: '/sthiti'
      preLoaderRoute: typeof SthitiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KalpanaRoute: KalpanaRoute,
  PraveshRoute: PraveshRoute,
  SamasyaRoute: SamasyaRoute,
  SthitiRoute: SthitiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
